### PR TITLE
Add Linux containers support

### LINKED ISSUE #30: Add support for Linux containers
Linux containers (e.g. LXD containers) have some particularity, notably the impossibility to use `chrony` (this is because containers use the guest OS time and are not allowed to modify it).

A simple playbook like `all_container.yml` without the call to `chrony.yml` can make the collection compatible with Linux containers.

### PR DESCRIPTION
**Pull request by Nuttymoon**
#### Which issue(s) this PR fixes:

Fixes #30 

#### Additional comments:

This PR adds a specific playbook for Linux container hosts. This can be useful for teams running TDP on LXD containers.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by rpignolet** [comment]
I wonder if this the good way to do it. I think a `facts` can have the information if we are in a container and disable the `chrony` playbook or tasks.

**Comment by gboutry** [comment]
> `facts`

We might look at the fact: `ansible_virtualization_type`, I don't know if it helps (on Openstack, it returns `openstack`...)

**Comment by Nuttymoon** [comment]
> > `facts`
> 
> We might look at the fact: `ansible_virtualization_type`, I don't know if it helps (
> 
> On my openstack vm it returns:
> 
> ```yaml
> ansible_virtualization_type: openstack
> ansible_virtualization_role: guest
> ```
> 
> On my host it returns:
> 
> ```yaml
> ansible_virtualization_type: kvm
> ansible_virtualization_role: host
> ```
> 
> On a LXD container it returns:
> 
> ```yaml
> ansible_virtualization_type: lxc
> ansible_virtualization_role: guest
> ```

Found an other variable `ansible_virtualization_tech_guest`:
```
ok: [edge-01] => 
  ansible_facts.virtualization_tech_guest:
  - lxc
  - container
```

**Comment by gboutry** [comment]
> > > `facts`
> > 
> > 
> > We might look at the fact: `ansible_virtualization_type`, I don't know if it helps (
> > On my openstack vm it returns:
> > ```yaml
> > ansible_virtualization_type: openstack
> > ansible_virtualization_role: guest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On my host it returns:
> > ```yaml
> > ansible_virtualization_type: kvm
> > ansible_virtualization_role: host
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On a LXD container it returns:
> > ```yaml
> > ansible_virtualization_type: lxc
> > ansible_virtualization_role: guest
> > ```
> 
> Found another variable `ansible_virtualization_tech_guest` which might be more generic. Not sure that its available on all Ansible versions:
> 
> ```
> ok: [edge-01] => 
>   ansible_facts.virtualization_tech_guest:
>   - lxc
>   - container
> ```

`virtualization_tech_guest` returns `[]` on my host (which is normal since it's an Host machine
On openstack the fact is missing

**Comment by Nuttymoon** [comment]
> ```yaml
> ansible_virtualization_type
> ```

Ok let's stick with `ansible_virtualization_type` then.

**Comment by Nuttymoon** [comment]
Forced push to only call the `chrony` role when host is not a Linux container.

**Review by gboutry — APPROVED** [review]

**Pull request merged**
