### PR TITLE
feat: add roles "system" and "chrony"

### LINKED ISSUE #2: Add system role
This role should configure
- `/etc/hosts`
- install required `yum` packages
- configure `JAVA_HOME`
- install required `pip3` dependencies

This role should support using a HTTP proxy.

### PR DESCRIPTION
**Pull request by rpignolet**
`system` role configure `/etc/hosts`, yum package and pip3 dependencies.

#### Which issue(s) this PR fixes:

Fixes #2 #3

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by Nuttymoon** [comment]
Shouldn't this collection be compatible with `tdp-lib` with `tdp_lib_dag` and `tdp_vars_defaults` so that deployments can be managed easily?

**Comment by rpignolet** [comment]
> Shouldn't this collection be compatible with `tdp-lib` with `tdp_lib_dag` and `tdp_vars_defaults` so that deployments can be managed easily?

This collection can be compatible with `tdp-lib` DAG but do we want to do prerequisites with the DAG ? This will add complexity to maintain and for now we can not add dependencies to existing components without redefine it.

**Review by gboutry — APPROVED** [review]

**Comment by Nuttymoon** [comment]
> > Shouldn't this collection be compatible with `tdp-lib` with `tdp_lib_dag` and `tdp_vars_defaults` so that deployments can be managed easily?
> 
> This collection can be compatible with `tdp-lib` DAG but do we want to do prerequisites with the DAG ? This will add complexity to maintain and for now we can not add dependencies to existing components without redefine it.

I guess that services within this collection could have dependencies on each other.

**Comment by gboutry** [comment]
> > > Shouldn't this collection be compatible with `tdp-lib` with `tdp_lib_dag` and `tdp_vars_defaults` so that deployments can be managed easily?
> > 
> > 
> > This collection can be compatible with `tdp-lib` DAG but do we want to do prerequisites with the DAG ? This will add complexity to maintain and for now we can not add dependencies to existing components without redefine it.
> 
> I guess that services within this collection could have dependencies on each other.

In my opinion, prerequisites are moved to clear tdp-getting-started and be shown as an example, but they are not meant to be managed as a TDP service.

I'm against adding `tdp_lib_dag` and `tdp_vars_defaults`

**Comment by leopaul36** [comment]
> I am just concerned about the impact on `tdp-getting-started`'s accessibility if we use some collections that are not `tdp-lib` compatible. This means that users will have to use both `ansible-playbook` and `tdp XXX` commands, and the `tdp-getting-started` file structure will be more complicated than if it was relying on `playbooks/meta` + `tdp_lib_dag` for all collections.

IMO this should not be an issue if our documentation states clearly what **is** in the TDP scope (ie: managed by `tdp`) and what **isn't**. We should make it very clear that we don't *support* the pre-requisites roles and that they are proposed as is as a way to get started more easily. Just like the Vagrant role is offered to get started on local, VMs, etc.

Thus I agree ith @rpignolet and @gboutry

**Comment by Nuttymoon** [comment]
Works for me.

**Review by Nuttymoon — APPROVED** [review]

**Pull request merged**
